#!/bin/sh

#Configure SSH User
echo root:$SSH_PASSWORD | chpasswd

#Configure SSH
sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config

#Start nginx
service nginx start


old_file_hash=''

if [ $NGINX_CONF_URL ]
then
  #Start SSH deamon
  #Load Balance
  /usr/sbin/sshd
  cd /etc/nginx
  while true; do
    rm nginx.tmp.conf
    wget $NGINX_CONF_URL -O nginx.tmp.conf
    current_file_hash=`md5sum nginx.tmp.conf | awk '{ print $1 }'`
    if [ "$current_file_hash" != "$old_file_hash" ]; then
      old_file_hash=$current_file_hash
      echo "Reloading nginx.conf file"
      cp nginx.tmp.conf nginx.conf
      nginx -s reload
    fi
    sleep 10
  done
else
  # Start SSH
  /usr/sbin/sshd -D
fi
