#!/bin/sh

#Configure SSH User
echo root:$SSH_PASSWORD | chpasswd

#Configure SSH
sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config

#Start nginx
service nginx start

# Start SSH
/usr/sbin/sshd -D
